stage-two/libgcrypt: disable asm on x86_64
When building x86_64 on a 32-bit host, the build fails with the error
below;

-------------------------------------------------------------------
libtool: link: x86_64-unknown-linux-musl-gcc -I/home/devel/zinja.git/sysroot/usr/include -fvisibility=hidden -Wall -o .libs/mpicalc mpicalc-mpicalc.o  -L/home/devel/zinja.git/sysroot/usr/lib -L/home/devel/zinja.git/sysroot/lib ./.libs/libgcrypt.so -lgpg-error -lcap
./.libs/libgcrypt.so: undefined reference to `_gcry_mpih_addmul_1'
./.libs/libgcrypt.so: undefined reference to `_gcry_mpih_rshift'
./.libs/libgcrypt.so: undefined reference to `_gcry_mpih_add_n'
./.libs/libgcrypt.so: undefined reference to `_gcry_mpih_mul_1'
./.libs/libgcrypt.so: undefined reference to `_gcry_mpih_submul_1'
./.libs/libgcrypt.so: undefined reference to `_gcry_mpih_lshift'
./.libs/libgcrypt.so: undefined reference to `_gcry_mpih_sub_n'
collect2: error: ld returned 1 exit status
Makefile:711: recipe for target 'mpicalc' failed
make[3]: *** [mpicalc] Error 1
-------------------------------------------------------------------

Disabling asm fixes the build failure

Signed-off-by: Mwanguhya Daniel Murungi <tuxmason@gmail.com>

(cherry picked from commit 0f5461cbb971be7bfeb7a45d8e03222184a86850)